/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { IQueryClientProvider, ISigningClientProvider, IMessageComposerProvider } from "./contractContextBase";
import { CwLottoQueryClient } from "./CwLotto.client";
import { CwLottoClient } from "./CwLotto.client";
import { CwLotto } from "./CwLotto.provider";
export interface IContractsContext {
  cwLotto: IQueryClientProvider<CwLottoQueryClient> & ISigningClientProvider<CwLottoClient>;
}
export const getProviders = (address?: string, cosmWasmClient?: CosmWasmClient, signingCosmWasmClient?: SigningCosmWasmClient) => ({
  cwLotto: new CwLotto({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  })
});