/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Duration = {
  height: number;
} | {
  time: number;
};
export type Uint128 = string;
export interface InstantiateMsg {
  admin: string;
  house_fee: number;
  lottery_duration: Duration;
  ticket_cost: Coin;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  buy_ticket: {
    num_tickets: number;
  };
} | {
  execute_lottery: {
    seed: number;
  };
} | {
  claim_tokens: {};
};
export type QueryMsg = {
  ticket_count: {
    addr: Addr;
  };
} | {
  lottery_state: {};
} | {
  config: {};
};
export type Addr = string;
export type Decimal = string;
export interface ConfigResponse {
  config: Config;
}
export interface Config {
  admin: Addr;
  house_fee: Decimal;
  ticket_unit_cost: Coin;
}
export type LotteryState = {
  OPEN: {
    expiration: Expiration;
    [k: string]: unknown;
  };
} | {
  CHOOSING: {
    [k: string]: unknown;
  };
} | {
  CLOSED: {
    claimed: boolean;
    winner: Addr;
    [k: string]: unknown;
  };
};
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface LotteryStateResponse {
  lotto_state: LotteryState;
  total_tickets: number;
}
export interface TicketResponse {
  tickets?: number | null;
}