/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CwLotto.types";
import * as _1 from "./CwLotto.client";
import * as _2 from "./CwLotto.provider";
export namespace contracts {
  export const CwLotto = { ..._0,
    ..._1,
    ..._2
  };
}