/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./HackCw20.types";
import * as _1 from "./HackCw20.client";
import * as _2 from "./CwLotto.types";
import * as _3 from "./CwLotto.client";
export namespace contracts {
  export const HackCw20 = { ..._0,
    ..._1
  };
  export const CwLotto = { ..._2,
    ..._3
  };
}