import Head from "next/head";
import {Button, Container, FormControl, FormLabel, Input,} from "@chakra-ui/react";
import {useCwLottoState} from "../hooks/use-cw-lotto-state";

import {useRouter} from 'next/router'
import React, {ChangeEvent, useEffect, useState} from "react";
import {CwLottoClient} from "../codegen/CwLotto.client";
import {useChain} from "@cosmos-kit/react";
import {chainName, CW_LOTTO_ADDRESS} from "../config";
import {func} from "prop-types";
import {LotteryState} from "../codegen/CwLotto.types";

export default function Admin() {
  const router = useRouter();

  const [client, setClient] = useState<CwLottoClient | null>(null);

  const {address, getSigningCosmWasmClient} = useChain(chainName);

  const lottoState = useCwLottoState(CW_LOTTO_ADDRESS);

  const [seedValue, setSeedValue] = useState<number | null>(null);
  const handleSeedChange = (event: ChangeEvent<HTMLInputElement>) => setSeedValue(event.target.value);

  useEffect(() => {
    if (!address) {
      return
    }
    getSigningCosmWasmClient()
      .then(signingCWClient => {
        if (!signingCWClient || !address) {
          console.error("cosmwasmClient undefined or address undefined.");
          return;
        }
        setClient(new CwLottoClient(signingCWClient, address, CW_LOTTO_ADDRESS));
      });
  }, [address, getSigningCosmWasmClient]);


  let adminComponent;

  const handleButtonClick = async () => {
    if (seedValue) {
      console.log(seedValue);
      let executeLottery = await client?.executeLottery({seed: seedValue});
      console.log(executeLottery);
    }

  };

  if (lottoState) {
    if ("CHOOSING" in lottoState) {
      adminComponent = <>
        <FormControl>
          <FormLabel>Seed For Random Lottery</FormLabel>
          <Input onChange={handleSeedChange}></Input>
        </FormControl>
        <Button onClick={handleButtonClick}>submit</Button>
      </>;
    } else if ("OPEN" in lottoState) {
      adminComponent = <div>still open</div>;
    } else { // CLOSED
      adminComponent = <div>closed</div>
    }
  }

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>CWLotto | Admin Panel</title>
        <meta name="description" content="Generated by create cosmos app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <div>

      </div>
      <div>
        {lottoState && adminComponent}
      </div>


    </Container>
  );
}
