import Head from "next/head";
import {Container} from "@chakra-ui/react";
import {useRouter} from 'next/router'

export default function AdminPage() {
  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>CW Lotto | Home</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        HOME-PAGE
    </Container>
  );
}
