import Head from "next/head";
import {
  Button,
  Container,
  FormControl,
  FormLabel, NumberDecrementStepper,
  NumberIncrementStepper,
  NumberInput, NumberInputField,
  NumberInputStepper,
} from "@chakra-ui/react";

import {useChain, useWallet} from "@cosmos-kit/react";

import {chainName, CW_LOTTO_ADDRESS, feeDenom, STAKINGDENOM} from "../config";

import {Coin} from "../codegen/CwLotto.types";

import {useRouter} from 'next/router'
import {useCwLottoState} from "../hooks/use-cw-lotto-state";
import {ChangeEvent, useEffect, useState} from "react";
import {CwLottoClient} from "../codegen/CwLotto.client";
import {GasPrice} from "@cosmjs/stargate";
import {getSigningCosmosClientOptions, getSigningCosmwasmClient} from "interchain";
// import {Coin} from "@keplr-wallet/unit";

/*
* If In progress then make it possible to buy tickets. Define how many inputted tickets enabled
* else:
* - trigger winning state
*
* */
// Call Contract, with defined address of smart contract. Grab the current state and
// depending on the state we can render a couple of UIs.
// Grab the contract
// - In Progress
// -> Buy tickets
// In Finals
// - Winner
// -
export default function Gamble() {
  const router = useRouter();

  const [client, setClient] = useState<CwLottoClient | null>(null);

  const [inputValue, setInputValue] = useState<any>(null);


  const { address, getSigningCosmWasmClient, getRestEndpoint, getRpcEndpoint, chain }= useChain(chainName);

  // console.log(chain.chain_id);

  const lottoState = useCwLottoState(CW_LOTTO_ADDRESS);

  useEffect(() => {
    getRpcEndpoint().then((resp => {
      console.log(resp)
    }));
    getRestEndpoint().then((resp => {
      console.log(resp)
    }));
  }, [address, getRestEndpoint, getRpcEndpoint]);



  useEffect(() => {
    if (!address) {
      return
    }
    getSigningCosmWasmClient()
      .then(signingCWClient => {
        if (!signingCWClient || !address) {
          console.error("cosmwasmClient undefined or address undefined.");
          return;
        }
        setClient(new CwLottoClient(signingCWClient, address, CW_LOTTO_ADDRESS));
      });
  }, [address, getSigningCosmWasmClient]);

  let lottoComponent;

  const handleInputChange = (event: ChangeEvent<HTMLInputElement>) => setInputValue(event.target.value);

  const handleButtonClick =   async () => {

    let buyTicket = await client?.buyTicket({numTickets: 1} );

    // console.log(buyTicket.logs);
    // Perform further actions with the input value
  };

  if (lottoState) {
    if ("OPEN" in  lottoState) {
      const openState = lottoState.OPEN;
      // hey you can vote and try and get tickets. =]

      console.log(lottoState.OPEN.expiration);

      // if open, see how many tickets we have bought.

      // render components that can then be executable.

      let fee: Coin = {
        amount: "1000", denom: STAKINGDENOM,
      };
      let expiration = openState.expiration;

      if ('at_time' in expiration) {
        const atTimeValue = expiration.at_time

        // if expiration time is after today, let the user update the state to the in progress to decide winner
        // for now, assume that they can vote.
        let expirationTime = new Date(Number(expiration.at_time) / 1e6)
        lottoComponent = <>
          We are open lotto state {expirationTime.toDateString()}

          <FormControl>
            <FormLabel>Amount</FormLabel>
            <NumberInput max={50} min={0}>
              <NumberInputField value={inputValue} onChange={handleInputChange} />
              <NumberInputStepper>
                <NumberIncrementStepper />
                <NumberDecrementStepper />
              </NumberInputStepper>
            </NumberInput>
          </FormControl>
          <Button onClick={handleButtonClick}>submit</Button>
        </>
      } else {
        console.error("We don't care")
      }

      // if a user can vote, he can enable somethings via the execute function so now we need
      // to do so this.
    } else if ('CHOOSING' in lottoState) {
      const choosingState = lottoState.CHOOSING;
      lottoComponent  = <div>
        We are waiting for admin to execute the winning lottery.
      </div>
    } else if ('CLOSED' in lottoState) {
      const closedState = lottoState.CLOSED;
      lottoComponent  = <div>
        Lotto is done
      </div>
    } else {
      console.error("Somehow got different lottoState")
    }
  } else {
    console.log("Value is undefined");
  }

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>CosmWasm Lotto</title>
        <meta name="description" content="Generated by create cosmos app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <div>{lottoComponent}</div>

    </Container>
  );
}
