import Head from "next/head";
import {Button, Container, Flex, useColorMode,} from "@chakra-ui/react";

import {useWallet} from "@cosmos-kit/react";

import {cw20ContractAddress} from "../config";
import {WalletSection,} from "../components";
import {useHackCw20Balance} from "../hooks/use-hack-cw20-balance";

import {useRouter} from 'next/router'

export default function Gamble() {
    const {walletStatus} = useWallet();
    const router = useRouter();
    return (
        <Container maxW="5xl" py={10}>
            <Head>
                <title>CosmWasm Lotto</title>
                <meta name="description" content="Generated by create cosmos app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Flex justifyContent="end" mb={4}>

            </Flex>
        </Container>
    );
}
