import Head from "next/head";
import {Container,} from "@chakra-ui/react";
import {PRIMARY_RUNNING_GAME} from "../config/lottery";
import {GameStateCard} from "../components/react/lotto-state-card";
import {useChain} from "@cosmos-kit/react";
import {chainName} from "../config";
import {ContractsProvider} from "../codegen/contracts-context";

const ContractComponent = ({children}: { children: any }) => {
  const {address, getCosmWasmClient, getSigningCosmWasmClient} = useChain(chainName);
  return (
    <ContractsProvider contractsConfig={{
      address,
      getCosmWasmClient,
      getSigningCosmWasmClient
    }}>
      {children}
    </ContractsProvider>
  );
};

const Layout = () => {
  const {status} = useChain(chainName);

  return (<Container maxW="5xl" py={10}>
    <Head>
      <title>CW Lotto | Home</title>
      <meta name="description" content="Generated by create cosmos app"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    {status === 'Connected' ? <GameStateCard contractAddress={PRIMARY_RUNNING_GAME} showPlayButton={false}/> :
      <div>Please connect your wallet.</div>}
  </Container>);
};

export default function Home() {
  /*
    * I want to show a list of all the underlying data from individual
    * lotteries. We should be able to sort them as well as.
    *
    * Wait a second. This is a product decision.
    * - should we have 1 individual running lottery or several running lotteries
    * - we should have one per denom token. we can have a list
    *   of individual previously listed items, but that's separate.
    *
    * json configuration:
    * - we'll have one primary and the rest list of previous per chain
    * */

  return (<ContractComponent>
    <Layout/>
  </ContractComponent>);
}
