import Head from "next/head";
import {Container, useColorMode,} from "@chakra-ui/react";

import {useWallet} from "@cosmos-kit/react";

import {useRouter} from 'next/router'

export default function Home() {
  const { walletStatus } = useWallet();

  const router = useRouter();
  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>CosmWasm Lotto</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*  TODO: Create a dashboard explaining how the lotto process works. and example screen shots*/}
    </Container>
  );
}
