import Head from "next/head";
import {Container, useColorMode,} from "@chakra-ui/react";

import {useWallet} from "@cosmos-kit/react";

import {useRouter} from 'next/router'

export default function Home() {
  const router = useRouter();

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>CW Lotto | Home</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        HOME-PAGE
    </Container>
  );
}
